version: "3.8"

services:
  mage:
    build:
      context: .
      dockerfile: ./mage/Dockerfile
    container_name: mage
    ports:
      - "6789:6789"
    volumes:
      - ./mage:/home/src
    environment:
      - USER_CODE_PATH=/home/src
    command: mage start mage_project
    depends_on:
      - mlflow
  mlflow:
    build:
      context: .
      dockerfile: ./mlflow/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "${PWD}/mlflow_data:/home/mlflow_data/"
